// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricLogger_PushMetric_FullMethodName = "/metrics.MetricLogger/PushMetric"
)

// MetricLoggerClient is the client API for MetricLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricLoggerClient interface {
	PushMetric(ctx context.Context, in *MetricData, opts ...grpc.CallOption) (*Response, error)
}

type metricLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricLoggerClient(cc grpc.ClientConnInterface) MetricLoggerClient {
	return &metricLoggerClient{cc}
}

func (c *metricLoggerClient) PushMetric(ctx context.Context, in *MetricData, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MetricLogger_PushMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricLoggerServer is the server API for MetricLogger service.
// All implementations must embed UnimplementedMetricLoggerServer
// for forward compatibility.
type MetricLoggerServer interface {
	PushMetric(context.Context, *MetricData) (*Response, error)
	mustEmbedUnimplementedMetricLoggerServer()
}

// UnimplementedMetricLoggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricLoggerServer struct{}

func (UnimplementedMetricLoggerServer) PushMetric(context.Context, *MetricData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMetric not implemented")
}
func (UnimplementedMetricLoggerServer) mustEmbedUnimplementedMetricLoggerServer() {}
func (UnimplementedMetricLoggerServer) testEmbeddedByValue()                      {}

// UnsafeMetricLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricLoggerServer will
// result in compilation errors.
type UnsafeMetricLoggerServer interface {
	mustEmbedUnimplementedMetricLoggerServer()
}

func RegisterMetricLoggerServer(s grpc.ServiceRegistrar, srv MetricLoggerServer) {
	// If the following call pancis, it indicates UnimplementedMetricLoggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricLogger_ServiceDesc, srv)
}

func _MetricLogger_PushMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricLoggerServer).PushMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricLogger_PushMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricLoggerServer).PushMetric(ctx, req.(*MetricData))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricLogger_ServiceDesc is the grpc.ServiceDesc for MetricLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricLogger",
	HandlerType: (*MetricLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMetric",
			Handler:    _MetricLogger_PushMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
