// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricCollectorService_SendMetric_FullMethodName       = "/digestlogger.metrics.MetricCollectorService/SendMetric"
	MetricCollectorService_SendMetricsBatch_FullMethodName = "/digestlogger.metrics.MetricCollectorService/SendMetricsBatch"
	MetricCollectorService_HealthCheck_FullMethodName      = "/digestlogger.metrics.MetricCollectorService/HealthCheck"
)

// MetricCollectorServiceClient is the client API for MetricCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricCollectorServiceClient interface {
	SendMetric(ctx context.Context, in *MetricData, opts ...grpc.CallOption) (*MetricResponse, error)
	SendMetricsBatch(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*MetricBatchResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type metricCollectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricCollectorServiceClient(cc grpc.ClientConnInterface) MetricCollectorServiceClient {
	return &metricCollectorServiceClient{cc}
}

func (c *metricCollectorServiceClient) SendMetric(ctx context.Context, in *MetricData, opts ...grpc.CallOption) (*MetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricResponse)
	err := c.cc.Invoke(ctx, MetricCollectorService_SendMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricCollectorServiceClient) SendMetricsBatch(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*MetricBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricBatchResponse)
	err := c.cc.Invoke(ctx, MetricCollectorService_SendMetricsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricCollectorServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MetricCollectorService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricCollectorServiceServer is the server API for MetricCollectorService service.
// All implementations must embed UnimplementedMetricCollectorServiceServer
// for forward compatibility.
type MetricCollectorServiceServer interface {
	SendMetric(context.Context, *MetricData) (*MetricResponse, error)
	SendMetricsBatch(context.Context, *MetricBatch) (*MetricBatchResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMetricCollectorServiceServer()
}

// UnimplementedMetricCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricCollectorServiceServer struct{}

func (UnimplementedMetricCollectorServiceServer) SendMetric(context.Context, *MetricData) (*MetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMetric not implemented")
}
func (UnimplementedMetricCollectorServiceServer) SendMetricsBatch(context.Context, *MetricBatch) (*MetricBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMetricsBatch not implemented")
}
func (UnimplementedMetricCollectorServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMetricCollectorServiceServer) mustEmbedUnimplementedMetricCollectorServiceServer() {
}
func (UnimplementedMetricCollectorServiceServer) testEmbeddedByValue() {}

// UnsafeMetricCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricCollectorServiceServer will
// result in compilation errors.
type UnsafeMetricCollectorServiceServer interface {
	mustEmbedUnimplementedMetricCollectorServiceServer()
}

func RegisterMetricCollectorServiceServer(s grpc.ServiceRegistrar, srv MetricCollectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetricCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricCollectorService_ServiceDesc, srv)
}

func _MetricCollectorService_SendMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricCollectorServiceServer).SendMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricCollectorService_SendMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricCollectorServiceServer).SendMetric(ctx, req.(*MetricData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricCollectorService_SendMetricsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricCollectorServiceServer).SendMetricsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricCollectorService_SendMetricsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricCollectorServiceServer).SendMetricsBatch(ctx, req.(*MetricBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricCollectorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricCollectorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricCollectorService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricCollectorServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricCollectorService_ServiceDesc is the grpc.ServiceDesc for MetricCollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricCollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digestlogger.metrics.MetricCollectorService",
	HandlerType: (*MetricCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMetric",
			Handler:    _MetricCollectorService_SendMetric_Handler,
		},
		{
			MethodName: "SendMetricsBatch",
			Handler:    _MetricCollectorService_SendMetricsBatch_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MetricCollectorService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
