// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MetricType            string                 `protobuf:"bytes,1,opt,name=metricType,proto3" json:"metricType,omitempty"`
	MethodName            string                 `protobuf:"bytes,2,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Timestamp             string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                 float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	UpstreamService       []string               `protobuf:"bytes,5,rep,name=upstreamService,proto3" json:"upstreamService,omitempty"`
	DownstreamService     []string               `protobuf:"bytes,6,rep,name=downstreamService,proto3" json:"downstreamService,omitempty"`
	UpstreamServiceLink   []string               `protobuf:"bytes,7,rep,name=upstreamServiceLink,proto3" json:"upstreamServiceLink,omitempty"`
	DownstreamServiceLink []string               `protobuf:"bytes,8,rep,name=downstreamServiceLink,proto3" json:"downstreamServiceLink,omitempty"`
	Service               string                 `protobuf:"bytes,9,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MetricData) Reset() {
	*x = MetricData{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricData) ProtoMessage() {}

func (x *MetricData) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricData.ProtoReflect.Descriptor instead.
func (*MetricData) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricData) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *MetricData) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *MetricData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MetricData) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricData) GetUpstreamService() []string {
	if x != nil {
		return x.UpstreamService
	}
	return nil
}

func (x *MetricData) GetDownstreamService() []string {
	if x != nil {
		return x.DownstreamService
	}
	return nil
}

func (x *MetricData) GetUpstreamServiceLink() []string {
	if x != nil {
		return x.UpstreamServiceLink
	}
	return nil
}

func (x *MetricData) GetDownstreamServiceLink() []string {
	if x != nil {
		return x.DownstreamServiceLink
	}
	return nil
}

func (x *MetricData) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\"\xda\x02\n" +
	"\n" +
	"MetricData\x12\x1e\n" +
	"\n" +
	"metricType\x18\x01 \x01(\tR\n" +
	"metricType\x12\x1e\n" +
	"\n" +
	"methodName\x18\x02 \x01(\tR\n" +
	"methodName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12(\n" +
	"\x0fupstreamService\x18\x05 \x03(\tR\x0fupstreamService\x12,\n" +
	"\x11downstreamService\x18\x06 \x03(\tR\x11downstreamService\x120\n" +
	"\x13upstreamServiceLink\x18\a \x03(\tR\x13upstreamServiceLink\x124\n" +
	"\x15downstreamServiceLink\x18\b \x03(\tR\x15downstreamServiceLink\x12\x18\n" +
	"\aservice\x18\t \x01(\tR\aservice\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2D\n" +
	"\fMetricLogger\x124\n" +
	"\n" +
	"PushMetric\x12\x13.metrics.MetricData\x1a\x11.metrics.ResponseB\bZ\x06proto/b\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metrics_proto_goTypes = []any{
	(*MetricData)(nil), // 0: metrics.MetricData
	(*Response)(nil),   // 1: metrics.Response
}
var file_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.MetricLogger.PushMetric:input_type -> metrics.MetricData
	1, // 1: metrics.MetricLogger.PushMetric:output_type -> metrics.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
